# address to which the server logs will be sent
# this needs to be reachable from the csgo server instances

listen_addr = "192.168.1.37"

# confinebot will allocate one port per match to listen to
# the server logs sent by csgo server instances

log_port_range = [25555, 26000]
