openapi: 3.0.1
info:
  title: Confinebot
  version: 1.0.0
paths:
  /match:
    get:
      summary: List all matches
      operationId: listMatch
      responses:
        200:
          description: A list of matches
          content:
            application/json:
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/Match'
    post:
      summary: Create a new match
      operationId: createMatch
      requestBody:
        description: Pet object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Match'
        required: true
      responses:
        200:
          description: The details of the match
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'
components:
  schemas:
    Team:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        nationality:
          type: string
    Match:
      type: object
      properties:
        id:
          type: integer
          format: int64
        teamA:
          $ref: '#/components/schemas/Team'
        teamB:
          $ref: '#/components/schemas/Team'
        password:
          type: string
        map:
          type: string
        mapSelectionMode:
          type: string
          enum:
          - BO1
          - BO3
        maxRounds:
          type: integer
          format: int64
        overtime:
          type: boolean
          default: false
        knifeRound:
          type: boolean
          default: true
        streamerReady:
          type: boolean
          default: false
        playAllRounds:
          type: boolean
          default: false
        autostartMatch:
          type: boolean
          default: false
        firstSide:
          type: string
          enum:
          - ACTBT
          - BCTAT
          - random
